### ISSUE TITLE
GPS not shown in the GPS page with a telemetry communication with INAV Configurator 6.0

### ISSUE THREAD

**Issue by wdliu356** [iNavFlight/inav-configurator#1752]
Hi, I'm building a 4 inch quad with MatekH743 flight controller board, mRo GPS u-Blox Neo-M8N IST8308 as my GPS and magnetometer. I'm also using RFD 900x-US as my telemetry radio for remote communication with the INAV configurator.
GPS shows well in the Setup page as is shown in the following figure.

<img width="1120" alt="image" src="https://user-images.githubusercontent.com/99144386/229897116-d03a02fb-e654-4494-ab0e-3aed088d9f7b.png">

But on the GPS page and the Mission Control Page, the drone cannot localize itself on the map, shown in the following two figures.

<img width="1120" alt="image" src="https://user-images.githubusercontent.com/99144386/229895929-9a4d0777-7b00-4b37-a1c1-3577a49fb1b4.png">
<img width="1115" alt="image" src="https://user-images.githubusercontent.com/99144386/229896859-78d69a45-8ed8-4b6b-93a1-5827d409b87b.png">

The ports page is shown as follows:
<img width="973" alt="image" src="https://user-images.githubusercontent.com/99144386/229898341-73eac044-d0bf-439f-ab1d-52643909ab46.png">

Everything is god when I'm using a wired communication between the my drone and laptop but wireless one is just not working that well. I checked that there was a similar issue posted in the inav repo and collaborators asked that person to repost that to the configurator repo but I can't find the repost so I post another issue here.

**Comment by OptimusTi** [comment]
Your telemetry radio too "loud" for the GPS?

**Comment by OptimusTi** [comment]
Oh, I didn't notice the 3d fix. Are you using an rx system that may limit telemetry sync like exprlrs or something like that? Check the telemetry settings and try UBLOX7

**Comment by OptimusTi** [comment]
Oh, I didn't notice the 3d fix. Are you using an rx system thatt may limit telemetry readings like exprlrs or something like that?

**Comment by wdliu356** [comment]
Which telemetry do you mean? Do you mean the telemetry connection with the ground station or the one with a remote controller? For that with the remote controller, yes, I'm using an Rx system. Will that affect that much? Since even if I didn't connect with the remote controller, it still doesn't show the GPS stuff

**Comment by OptimusTi** [comment]
Which rx system?

**Comment by wdliu356** [comment]
Just wanna double check when you are talking about rx system, you mean communicating by rx and tx ports right?

**Comment by MrD-RC** [comment]
He means the RF link. The transmitter and receiver you are using for the RC communication.

**Comment by wdliu356** [comment]
The telementry radio for remote controller I'm using is TBS crossfire nano rx. Any clue for that?

**Comment by OptimusTi** [comment]
Yeah I have the same setup and it's working. I'm on 7.0 but it should be the same. I'm going to get install 6.0 and let you know

**Comment by OptimusTi** [comment]
Confirmed. Works in 6.0. I'd reinstall your configurator and check wiring.
![image](https://user-images.githubusercontent.com/45466510/231477030-81898084-53b4-4097-a0cb-005efcb22dde.png)

**Comment by wdliu356** [comment]
Do you have any idea about what kind of wiring problem can lead to such a problem? I tried both INav 5 and 6 and both of them share the same problem so I would think it might be the wiring issue. Am I supposed to focus on the wiring of the telemetry radio?

**Comment by OptimusTi** [comment]
At this point, I'd reinstall the configurator. Looks like the GPS is communicating with the FC.

**Comment by wdliu356** [comment]
And another interesting is that though it shows no gps fix on the GPS page and no point on the current location, when I click the 'center', it centers on the correct place. When I zoom in the map, it shows the correct area I'm currently at. But still not showing GPS fix

**Comment by OptimusTi** [comment]
> May I check what system are you working on? Windows or Linux? I'm working at Windows system and tried both the .exe file and the zip file of the release. But it still seems not showing on the GPS page

I'm on latest Windows 10. I installed 6.0 using the Windows installer INAV-Configurator_win64_6.0.0.exe

**Comment by wdliu356** [comment]
> And another interesting is that though it shows no gps fix on the GPS page and no point on the current location, when I click the 'center', it centers on the correct place. When I zoom in the map, it shows the correct area I'm currently at. But still not showing GPS fix

I also tried that on a linux machine and it shares the same problem. 
It can locate itself but it will not show its position on the map and shows no 3d fix on the GPS page.

**Comment by wdliu356** [comment]
Another thing is that, with the current setup, I lost the communication with the drone after I arm it

**Comment by wdliu356** [comment]
I've actually done this several times but nothing changed. I believe I'm not the only one meeting this issue.
https://github.com/iNavFlight/inav/issues/4553
The link is another person sharing the same issue with me. This might be a hidden bug that has been there for many years maybe?

**Comment by wdliu356** [comment]
Hey, I just fixed issue by not clicking the wireless mode when connecting with the drone, though I'm doing that through telemetry. Maybe you need to double check that button or record that in the readme.

**Comment by OptimusTi** [comment]
I'm still not having the issue even if I select wireless mode. Works fine here.
