### ISSUE TITLE
x64 Mac version of 9.0 is corrupted

### ISSUE THREAD

**Issue by sboicu** [iNavFlight/inav-configurator#2457]
I try to install 9.0 from both dmg and zip file and both are corrupted. i tried multiple times.
In the zip file i manage to extract but there is a exe file not somthing i can use on mac.
any ideas?

<img width="951" height="511" alt="Image" src="https://github.com/user-attachments/assets/03bdf540-0de1-4e9e-bcaf-891822065f9b" />

**Comment by hv6jpkwmvk-sys** [comment]
I had same problem and when trying to open the arm64, Apple would not let it open because they said it has not been checked for Malware and to move it to the trash

**Comment by sensei-hacker** [comment]
The packaging error in the RC was fixed for the 9.0.0 release on January 16. Closing.

**Comment by stronnag** [comment]
The release archive is:
* A valid, readble, extractable `dmg` file; and
* The binary, executable items in the file are Arm64 binaries

```
$ cd INAV\ Configurator.app/
 $ find . -type f -a -executable -print0 | xargs -0 file | grep -v ASCII | grep -v node
./Contents/Resources/sitl/macos/inav_SITL:                                                                                         Mach-O universal binary with 2 architectures: [x86_64:\012- Mach-O 64-bit x86_64 executable, flags:<NOUNDEFS|DYLDLINK|TWOLEVEL|WEAK_DEFINES|BINDS_TO_WEAK|PIE>] [\012- arm64:\012- Mach-O 64-bit arm64 executable, flags:<NOUNDEFS|DYLDLINK|TWOLEVEL|WEAK_DEFINES|BINDS_TO_WEAK|PIE>]
./Contents/MacOS/inav-configurator:                                                                                                Mach-O 64-bit arm64 executable, flags:<NOUNDEFS|DYLDLINK|TWOLEVEL|PIE>
./Contents/Frameworks/Squirrel.framework/Versions/A/Squirrel:                                                                      Mach-O 64-bit arm64 dynamically linked shared library, flags:<NOUNDEFS|DYLDLINK|TWOLEVEL|NO_REEXPORTED_DYLIBS>
./Contents/Frameworks/Squirrel.framework/Versions/A/Resources/ShipIt:                                                              Mach-O 64-bit arm64 executable, flags:<NOUNDEFS|DYLDLINK|TWOLEVEL|PIE>
./Contents/Frameworks/ReactiveObjC.framework/Versions/A/ReactiveObjC:                                                              Mach-O 64-bit arm64 dynamically linked shared library, flags:<NOUNDEFS|DYLDLINK|TWOLEVEL|NO_REEXPORTED_DYLIBS>
./Contents/Frameworks/Mantle.framework/Versions/A/Mantle:                                                                          Mach-O 64-bit arm64 dynamically linked shared library, flags:<NOUNDEFS|DYLDLINK|TWOLEVEL|NO_REEXPORTED_DYLIBS>
./Contents/Frameworks/INAV Configurator Helper.app/Contents/MacOS/INAV Configurator Helper:                                        Mach-O 64-bit arm64 executable, flags:<NOUNDEFS|DYLDLINK|TWOLEVEL|PIE|HAS_TLV_DESCRIPTORS>
./Contents/Frameworks/INAV Configurator Helper (Renderer).app/Contents/MacOS/INAV Configurator Helper (Renderer):                  Mach-O 64-bit arm64 executable, flags:<NOUNDEFS|DYLDLINK|TWOLEVEL|PIE|HAS_TLV_DESCRIPTORS>
./Contents/Frameworks/INAV Configurator Helper (Plugin).app/Contents/MacOS/INAV Configurator Helper (Plugin):                      Mach-O 64-bit arm64 executable, flags:<NOUNDEFS|DYLDLINK|TWOLEVEL|PIE|HAS_TLV_DESCRIPTORS>
./Contents/Frameworks/INAV Configurator Helper (GPU).app/Contents/MacOS/INAV Configurator Helper (GPU):                            Mach-O 64-bit arm64 executable, flags:<NOUNDEFS|DYLDLINK|TWOLEVEL|PIE|HAS_TLV_DESCRIPTORS>
./Contents/Frameworks/Electron Framework.framework/Versions/A/Libraries/libvk_swiftshader.dylib:                                   Mach-O 64-bit arm64 dynamically linked shared library, flags:<NOUNDEFS|DYLDLINK|TWOLEVEL|NO_REEXPORTED_DYLIBS|HAS_TLV_DESCRIPTORS>
./Contents/Frameworks/Electron Framework.framework/Versions/A/Libraries/libGLESv2.dylib:                                           Mach-O 64-bit arm64 dynamically linked shared library, flags:<NOUNDEFS|DYLDLINK|TWOLEVEL|NO_REEXPORTED_DYLIBS|HAS_TLV_DESCRIPTORS>
./Contents/Frameworks/Electron Framework.framework/Versions/A/Libraries/libffmpeg.dylib:                                           Mach-O 64-bit arm64 dynamically linked shared library, flags:<NOUNDEFS|DYLDLINK|TWOLEVEL|NO_REEXPORTED_DYLIBS>
./Contents/Frameworks/Electron Framework.framework/Versions/A/Libraries/libEGL.dylib:                                              Mach-O 64-bit arm64 dynamically linked shared library, flags:<NOUNDEFS|DYLDLINK|TWOLEVEL|NO_REEXPORTED_DYLIBS|HAS_TLV_DESCRIPTORS>
./Contents/Frameworks/Electron Framework.framework/Versions/A/Helpers/chrome_crashpad_handler:                                     Mach-O 64-bit arm64 executable, flags:<NOUNDEFS|DYLDLINK|TWOLEVEL|WEAK_DEFINES|BINDS_TO_WEAK|PIE|HAS_TLV_DESCRIPTORS>
./Contents/Frameworks/Electron Framework.framework/Versions/A/Electron Framework:                                                  Mach-O 64-bit arm64 dynamically linked shared library, flags:<NOUNDEFS|DYLDLINK|TWOLEVEL|WEAK_DEFINES|BINDS_TO_WEAK|NO_REEXPORTED_DYLIBS|HAS_TLV_DESCRIPTORS>
```
So **this** issue **does not** persist with the 9.0.0 arm64 build.

**Comment by JeanBlignaut** [comment]
This issue persists for releases 9.0.2 and 9.0.1 (arm64 since that's what I need) 
I have verified the sha256sum of both and definitely the signing issue remains.

**Comment by sensei-hacker** [comment]
> That points to a packaging/signing issue (bundle contents not matching what was signed), typically caused by modifying the .app after signing or signing in the wrong stage of the build pipeline.

It is not signed.  See the bold notice marked **IMPORTANT** where you download it.

If you have a signing key -- welcome to the team!
